name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: eval-git-ci-js-base

      - name: Create reports folder
        run: mkdir -p eval-git-ci-js-base/reports

      - name: Run tests
        run: npm test
        working-directory: eval-git-ci-js-base
